CaptainPStar/co10_Escape

- Code/functions/Server/fn_createComCenters.sqf
The com center creation function was looping over the original (now empty) marker array rather than the shuffled version, resulting in no com centers.
Also sanitized spellings of the two array variables.
> Fix com center creation and spelling consistency

- Code/functions/Common/fn_initLocalPlayer.sqf
- Mods/CUP RU/UnitClasses.sqf
- Mods/CUP SLA/UnitClasses.sqf
- Mods/CUP Taki/UnitClasses.sqf
- Mods/CUP-BAF d/UnitClasses.sqf
- Mods/CUP-BAF w/UnitClasses.sqf
- Mods/CUP-CDF winter/UnitClasses.sqf
- Mods/CUP-US Army d/UnitClasses.sqf
- Mods/CUP-US USMC/UnitClasses.sqf
- Mods/Vanilla Apex US/UnitClasses.sqf
- Mods/Vanilla Apex/UnitClasses.sqf
- Mods/Vanilla US/UnitClasses.sqf
- Mods/Vanilla/UnitClasses.sqf
The UnitClasses.sqf file for many of the versions could use some updates, and I've started with three sections that I felt were most in need of it, which are Comcenter defense, helicoopters, and UAV.
These three sections were key points of balance that I felt needed some adjustment.  My primary goals were to make these consistent with each other in regards to difficulty, while still retaining each mods unique feel and unit types.  There were also a few units of the wrong side/type/etc that I wanted to fix when necessary.
Comcenter defense: I focused on removing heavily armored AA units away from the light classes into the heavy classes and ensuring the light classes were primarily heavily armored cars and wheeled APCs without tank turrets.  These changes will ensure a smoother difficulty …
> UnitClasses.sqf Updates

- Code/Scripts/Escape/EscapeSurprises.sqf
I discovered that motorized search group in EscapeSurprises.sqf was always spawning 2 vehicles that spawned into each other and exploded as a result.
Credit goes to John Jordan from discord for finding the duplicate line that caused the bug.
> Removed duplicate motorized search group entry

- Code/functions/Server/fn_initServer.sqf
With the escape surprises motorized search group working properly now, leaving in this is redundant and in my opinion adds an unnecessary difficulty spike, especially when war torn is disabled.
> Remove motorized search group from fn_initserver.sqf

- Missions/Tembelan/mission.sqm
tembelan island spawns with unplayably thick fog the majority of the time.  removing these lines fixes it
> fix tembelan fog issue

- Code/functions/Server/fn_initServer.sqf
- Configs/CUP.json
- Mods/CUP RU vs USMC-RACS/UnitClasses.sqf
It's based on the current SLA vs USMC version, but completely overhauled.  Some of the changes include:
-Changed Indep faction from NAPA to RACS
The NAPA being used in both the USMC and RU versions of escape in my opinion made these versions feel too similar.  The RACS is only used in one other version exclusive to Sahrani so this should make the version feel a lot different than the old SLA vs USMC version.  Since RACS mainly use US weapons, it makes looting and rearming a bit easier for the players.  The RACS do have a few weapons and vehicles the USMC don't so they still have some differences with the USMC and aren't just the USMC in a different uniform.
-Added all the new equipment added over the last few CUP update including dozens of new weapons, vehicles, scopes, items, ammunition, …
> Adding new CUP RU vs USMC and RACS Version

- Code/functions/Templates/fn_AmmoDepot2.sqf
Seems like it was an experimental change on some of the base templates that was commented out on all of them except one.
> Fix "Picture mapconfig\logo.paa not found" error

- Mods/CUP RU vs USMC-RACS/UnitClasses.sqf
- Mods/CUP Taki/UnitClasses.sqf
- Mods/CUP-CDF winter/UnitClasses.sqf
- Mods/Vanilla US/UnitClasses.sqf
- Mods/Vanilla/UnitClasses.sqf
Includes a complete rework of Vanilla, Vanilla US, CUP Taki, CUP-CDF winter, and I also added some adjustments to CUP RU vs USMC-RACS.
I've adjusted this in line with my new RU vs USMC and RACS version so they all have new weapons, units, and vehicles that have been added to the mods and the base game over the years and they have the new ratio for vehicle spawns that seems to be working pretty well.  I made sure to keep the low SMG count in the prison backpack that's currently in place for all versions.
> Unit Config reworks

- Code/functions/Server/fn_initServer.sqf
Fixed if statement that activated civilian reporting from stopping because a3e_var_Escape_SearchLeader_civilianReporting = false in fn_missionFlow.sqf
> - Fixed Civilian Reporting if statement

- Code/Scripts/Escape/CreateSearchChopper.sqf
Easy Little-Bird-like choppers become more dangerous.
I skipped `OnSpawnGeneralSoldierUnit` event for FFV units. 0.2-0.6 ammo is quite a little for soldiers in heli and due to arma bug soldiers don't rearm even there are their magazines in heli cargo.
Also I didn't add "eject on dead" code. It's quite fun, dead soldiers fall to ground like shot ducks from flying heli. But I didn't take a decision if it's good or bad. BTW "dead" can be for chopper: then soldiers could lie near crashed heli.
> Add search chopper FFV units

- Code/functions/Common/fn_initArsenal.sqf
- Code/functions/Templates/fn_AmmoDepot.sqf
- Code/functions/Templates/fn_AmmoDepot2.sqf
- Code/functions/Templates/fn_AmmoDepot3.sqf
- Code/functions/Templates/fn_AmmoDepot4.sqf
- Code/functions/Templates/fn_AmmoDepot5.sqf
- Code/include/functions.hpp
- Mods/CUP RU vs USMC-RACS/UnitClasses.sqf
- Mods/CUP RU/UnitClasses.sqf
- Mods/CUP-BAF d/UnitClasses.sqf
- Mods/CUP-BAF w/UnitClasses.sqf
- Mods/CUP-US Army d/UnitClasses.sqf
- Mods/CUP-US USMC/UnitClasses.sqf
When merged this pull request will:
- title;
- add lists to CUP RU and US/BAF configs.
Additional weapon boxes on ammo points contain all weapons from appropriate side. We can add arsenal to these boxes with configured weapons/mags from this side.
Weapons are generated both from cfgPatches and weapons lists. cfgPatches allow to simplify lists very much. At least vanilla, CUP and RHS weapons are grouped to per-side configs and can be used this way.
Lists are not mandatory to present in UnitClasses. If there isn't lists in config, arsenal won't be added.
> Add Virtual Arsenal to additional weapon boxes

- Code/functions/Server/fn_createMotorPool.sqf
- Code/functions/Templates/fn_BuildMotorPool.sqf
I've been using these values on my server for a while and I think they greatly improve the gameplay and functionality of the Motorpool.
I changed the heavy vehicle to spawn with more fuel since 1% for some vehicles is barely enough to move a couple hundred meters.  To compensate for this I adjusted the damage values to start at a higher value and can go up to a much higher value.
I changed the second vehicle from always being a civilian vehicle to being one from the `a3e_arr_ComCenParkedVehicles` array.  It never made much sense why a civilian vehicle is in the motorpool and this feels much more immersive and is more useful for the players without being too overpowered.
I also increased the chance of the the other two vehicles spawning and I changed the one that always spawns as a …
> changing motorpool spawns/ammo/fuel/damage

- Code/functions/Common/fn_checkUnitClasses.sqf
Function dumps "bad" classes to RPT.
Usage:
```
call compile preprocessFileLineNumbers "functions\Common\fn_checkUnitClasses.sqf"
```
I'm not sure if it needs to be in CfgFunctions because it's not used during game. The same is for `Common` category/folder.
I decreased scope requirement for vehicles (>=1 is OK for now). Looks like there are too many scope==1 vehicles.
Compatible with #58.
> Add function for unit classes check

- Code/functions/Templates/fn_BuildComCenter.sqf
ComCenter template has `HeliHEmpty` which is missing in A3. If it wasn't ever in A3 then it's not needed.
> Remove HeliHEmpty

- Configs/CUP.json
- Mods/CUP RU vs US Army-Taki GUE/Unitclasses.sqf
- Mods/CUP SLA vs HIL-RACS/Unitclasses.sqf
With the latest CUP update adding a new faction and a bunch of changes to the US Army/USMC and the previous one adding a ton of vehicles to the Taki GUE faction I decided to make some new versions to take advantage of the new gear.
The CUP RU vs US Army-Taki GUE has the players using the new Ratnik pink desert uniforms mostly because they're so unique.  The main opposing faction is the US Army and the secondary is the Takistani Guerrillas.  It has a lot of weapon variety and it's interesting to see such contrast between the opposing factions, especially with wartorn on. I've added this version to desert maps.
The CUP SLA vs HIL-RACS has the players as the Sahrani Liberation Army with the default uniforms against the new Horizon Islands Legion with their default uniforms and the Royal Army …
> New CUP RU vs US Army-Taki GUE and CUP SLA vs HIL-RACS versions

- Code/functions/Spawning/fn_onEnemySoldierSpawn.sqf
Original fix was from Dystopian, however it broke in the past few months.  Implemented this fix with some help from NeoArmageddon.
> Remove NVG from units vest/uniform when NVG Param is off

- Missions/Ruha/mission.sqm
Seems like when month is set to Jan/Feb/Mar/Dec thermal imaging completely breaks on this map. Changing it to any other month fixes it. I still kept the full moon night.
I checked Anizay and Summa and they didn't seem to have the same issue.
Here's some screenshots demonstrating the issue: https://imgur.com/a/G7JBkWQ
> workaround for Ruha Thermal Imaging Bug

- Missions/Fallujah/mission.sqm
Made this in August of 2019 and completely forgot to upload it to the main repository.  I've been playing it since then and it's a blast.  The main changes is I moved all of the in city extraction points to zones outside of the city.  I didn't put them on the edge of the map and put them more towards the center with cover from nearby buildings or hills.  They're still at risk from incoming attacks for some challenge, but are much safer overall.
I remember trying to put one of the extraction points in a walled off factory area but the helicopters simply _refused_ to land on the zones and instead landed on buildings or other objects, so I had to move it elsewhere.
I also changed the date so that there's a near full moon for most of the night so you can see better.  Full cloud cover can …
> Fallujah extraction edit and date adjustment

- Code/Scripts/AT/dronehack_init.sqf
- Code/Scripts/AT/hackdrone.sqf
- Code/functions/Common/fn_initLocalPlayer.sqf
This feature was removed in 8636853b434d3331be37ed839eb56b7a2854f649 due to some issues. But I learned in the meantime that there's actually a [hacking mechanic](https://armedassault.fandom.com/wiki/Hacking_(electronics)) in the game itself, so for the most part it shouldn't be necessary anyway.
The only trouble is that it's impossible to get your hands on a UAV terminal for your own faction, so what we'd need is the ability to convert an enemy UAV terminal into a friendly one. To do that I reintroduced only the necessary portion of the original script and also fixed the issue that caused the player action to appear twice.
I'm not sure if that's the original problem that got this removed, but in any case I won't be disappointed if you decide not to merge this. I'm happy enough to keep it …
> Re-enable UAV terminal hacking

- compile.py
I noticed that `compile.py` would fail on a freshly cloned repository, because not all subdirectories required for the build process were created. I changed the single line in the script to do what was probably the original intention anyway.
> Create all required build directories

- Code/functions/Common/fn_checkUnitClasses.sqf
- Code/functions/Common/fn_loadLocalClasses.sqf
- Code/functions/Server/fn_initServer.sqf
- Code/include/functions.hpp
This PR allows server administrator to add own classes to mission arrays without mission recompiling.
E.g. he wants to add `TGA-200F` civilian scooters for mission with any mod, add `Tigr` and `T-90M` from `[DEV] CUP` to `CUP Woodland USMC vs RU and NAPA` missions, and add `KA-137` UAV to `CUP Woodland RU vs BAF and ION PMC` missions. This configuration can be like this:
```
profileNamespace setVariable ["A3E_Classes", [
["CUP Woodland USMC vs RU and NAPA", [
["a3e_arr_Escape_MilitaryTraffic_EnemyVehicleClasses", [
"CUP_O_Tigr_233011_GREEN_RU",
"CUP_O_Tigr_233014_PK_RU",
"CUP_O_Tigr_M_233114_RU"
]],
["a3e_arr_Escape_RoadBlock_MannedVehicleTypes", [
"CUP_O_Tigr_233014_GREEN_PK_RU",
"CUP_O_Tigr_M_233114_KORD_RU",
"CUP_O_Tigr_M_233114_PK_RU"
]],
["a3e_arr_ComCenDefence_heavyArmorClasses", …
```
> Add per-server classes support

- Configs/CUP.json
Old units are `scope=1` in CUP 1.18 and mission is not loaded.
Credits go to Jugger.
> Fix missions with CUP russian desert player units
